import {Cookie} from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import {SiAng} from "react-icons/si"


const adebare = Cookie({ subsets: ["latin"],weight:'400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"className="" >
      <body className={adebare.className}>
        <Navbar/>
        <div className="h-[1300vh]">
        {children}
        </div>
        
        
        <Footer/>
        </body>
    </html>
  );
}
